---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: BigIP F5 UCS backup
  hosts: localhost
  connection: local
  vars_files: vars/main.yml
  gather_facts: no
  tasks:
  #  - include_vars: ../defaults/main.yml

    - name: Set Provider BigIP F5 Data
      set_fact:
        f5_provider:
            server: "{{ hostvars[groups['bigipf5'][0]].network_interfaces[0].association.public_ip }}"
            server_port: 443
            user: "{{ ec2_bigipf5_user }}"
            password: "{{ ec2_bigipf5_pass }}"
            validate_certs: no
            no_f5_teem: false

    - debug: 
        var: f5_provider 

    - name: Create backup UCS (User Configuration Set)
      f5networks.f5_modules.bigip_ucs_fetch:
        provider: "{{ f5_provider }}"
        backup: yes
        only_create_file: no
        dest: /tmp/backup.ucs
      register: backupinfo

    - name: Debug backup content
      debug:
        var: backupinfo

- name: Store files via scp
  hosts: backup-server
  connection: ssh
  vars_files: vars/main.yml
  tasks:
  #  - include_vars: ../defaults/main.yml

    - name: Create backup folder on backup server
      ansible.builtin.file:
        path: "{{ backup_server_folder }}"
        state: directory
      become: true

    - name: Copy config to backup server
      copy:
        src: "/tmp/backup.ucs"
        dest: "{{ backup_server_folder }}f5-{{ '%Y-%m-%dT%H:%M:%S' | strftime(ansible_date_time.epoch) }}"
      become: true


