---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: BigIP F5 provisioning
  hosts: localhost
  connection: local
  vars_files: vars/main.yml
  gather_facts: no

  tasks:

    - debug:
        var: hostvars[groups['bigipf5'][0]]

    - debug:
        var: hostvars[groups['bigipf5']]

    - name: Set Provider Infoblox Data
      set_fact:
        f5_provider:
            host: "{{ hostvars[groups['bigipf5'][0]].network_interfaces[0].association.public_ip }}"
            username: "{{ ec2_bigipf5_user }}"
            password: "{{ ec2_bigipf5_pass }}"

    - name: Debug Provider BigIP F5 Data (Public IP, Username, Password) 
      debug:
        var: f5_provider

    - name: gather facts
      f5networks.f5_modules.bigip_device_info:
        provider: "{{ f5_provider }}"
        gather_subset: "{{ f5_device_info_subset }}"
      register: _f5_facts

    - name: Device Info output
      debug: 
        msg: "{{ _f5_facts }}"
