---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: BigIP F5 provisioning
  hosts: localhost
  connection: local
  vars_files: vars/main.yml
  gather_facts: no  
  tasks:
    - name: Set Provider BigIP F5 Data
      set_fact:
        f5_provider:
            server: "{{ hostvars[groups['bigipf5'][0]].network_interfaces[0].association.public_ip }}"
            server_port: 443
            user: "{{ ec2_bigipf5_user }}"
            password: "{{ ec2_bigipf5_pass }}"
            validate_certs: no
            no_f5_teem: false

    - name: Delete Virtual Server
      bigip_virtual_server:
        provider: "{{ f5_provider }}"
        name: "{{ item.name }}"
        destination: "{{ f5_provider.server }}"
        port: "{{ item.port }}"
        enabled_vlans: "{{ item.enabled_vlans }}"
        all_profiles: "{{ item.all_profiles }}"
        pool: "{{ item.pool }}"
        snat: "{{ item.snat }}"
        state: absent
      loop: "{{ virtual_servers }}"

    - name: Delete Pool Members
      bigip_pool_member:
        provider: "{{ f5_provider }}"
        port: "{{ item.port }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: "{{ item.pool }}"
        state: absent
      loop: "{{ pool_members }}"

    - name: Delete F5 Pools
      bigip_pool: 
        provider: "{{ f5_provider }}"
        name: "{{ item.name }}"
        lb_method: "{{ item.lb_method }}"
        monitors: "{{ item.monitors }}"
        monitor_type: "{{ item.monitor_type }}"
        state: absent
      loop: "{{ pools }}"

    - name: Delete F5 Nodes
      bigip_node:
        provider: "{{ f5_provider }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        state: absent
      loop: "{{ nodes }}"

    - name: save config
      bigip_config:
        provider: "{{ f5_provider }}"
        save: yes
