---

# - name: Refresh inventory
#   ansible.builtin.meta: refresh_inventory
  
- name: Get BigIP F5 node
  set_fact:
    node_name: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: hostvars[item].tags is defined and hostvars[item].tags.Name | regex_search("^bigipf5-(.*)$")

- name: Add BigIP F5 node to the bigipf5 group
  add_host:
    name: "{{ node_name }}"
    groups: "bigipf5"
  when: node_name is defined

- name: Add RHEL node to the rhel group
  add_host:
    name: "{{ node_name }}"
    groups: "rhel"
  when: node_name is defined
