# VPC
ec2_vpc_name: VPC_F5
ec2_vpc_region: us-east-1
ec2_vpc_cidr: 10.0.0.0/16
# Subnets
ec2_subnet_az: us-east-1a
ec2_subnet_name_mgmt: Subnet_F5_MGMT
ec2_subnet_cidr_mgmt: 10.0.0.0/24
ec2_subnet_name_srv: Subnet_F5_SRV
ec2_subnet_cidr_srv: 10.0.1.0/24
# ENIs
ec2_eni_name_srv: ENI_F5_SRV
ec2_eni_name_mgmt: ENI_F5_MGMT
# Elastic IP
ec2_eip_name_mgmt: EIP_F5_MGMT
# IGW
ec2_igw_name: IGW_F5
# Route Table
ec2_rt_name: RT_F5
# RHEL Open ports
ec2_sg_name: SG_F5
ec2_sg_openports:
  - 80
  - 443
  - 22
  - 514
  - 541
  - 542
  - 9433

# BigIP F5
ec2_bigipf5_instance_name: bigipf5-1
ec2_bigipf5_image_id: ami-0622a3d7a285429de
ec2_bigipf5_image_name: bigipf5 NIOS 9.0.5(BYOL)-3d6f2259-6756-484c-ac5e-f2d9330afe95
ec2_bigipf5_flavor_name: m5.large #m6i.2xlarge 
ec2_bigipf5_keypair_name: "KeyPair-Virginia"
ec2_bigipf5_admin_pass: "{{ ansible_ssh_pass }}"
volumes:
  - device_name: /dev/sda1
    ebs:
      volume_type: gp3
      volume_size: 500
      delete_on_termination: true
  - device_name: /dev/sdb
    ebs:
      volume_type: gp3
      volume_size: 500
      delete_on_termination: true
