---

- name: BigIP F5 provisioning
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - include_vars: ../defaults/main.yml
    #- include_vars: ../vaults/f5_vault.yml

    - name: Include license
      include_tasks: license.yml
      tags: license
      
    - name: Include facts
      include_tasks: facts.yml
      tags: facts

    - name: Include load balance
      include_tasks: balance.yml

    - include_tasks: postprovision.yml
      tags: [postprovision, prepare]

    - include_tasks: balance.yml 
      tags: [balance]

    - include_tasks: poolmember.yml
      tags: [poolmember]

    - include_tasks: poolreport.yml
      tags: [report]

    #- include_tasks: 
    #    file: reverseengineer.yml
    #    apply: 
    #      tags: always
    #  tags: [reverse]

    #- name: Revoke license
    #  include_tasks: revoke_license.yml
    #  tags: license

