---

- name: BigIP F5 provisioning
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - include_vars: ../defaults/main.yml

    - name: Create F5 Nodes
      bigip_node:
        provider: "{{ f5_provider }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        state: present
      loop: "{{ nodes }}"

    - name: Create F5 Pools
      bigip_pool: 
        provider: "{{ f5_provider }}"
        name: "{{ item.name }}"
        lb_method: "{{ item.lb_method }}"
        monitors: "{{ item.monitors }}"
        monitor_type: "{{ item.monitor_type }}"
        state: present
      loop: "{{ pools }}"

    - name: Add Pool Members
      bigip_pool_member:
        provider: "{{ f5_provider }}"
        port: "{{ item.port }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: "{{ item.pool }}"
        state: present
      loop: "{{ pool_members }}"

    - name: Add Virtual Server
      bigip_virtual_server:
        provider: "{{ f5_provider }}"
        name: "{{ item.name }}"
        destination: "{{ f5_provider.server }}"
        port: "{{ item.port }}"
        enabled_vlans: "{{ item.enabled_vlans }}"
        all_profiles: "{{ item.all_profiles }}"
        pool: "{{ item.pool }}"
        snat: "{{ item.snat }}"
        state: present
      loop: "{{ virtual_servers }}"
      register: vservercache

    - name: Delay after virtual server changed
      wait_for:
        timeout: 5
      when: vservercache.changed

    - name: save config
      bigip_config:
        provider: "{{ f5_provider }}"
        save: yes
